Added validation to the promo code field
PrudinnikDmitriy/Adding-validation-to-the-promo-code-field pull request #1
Opened 2022-10-27 12:50 UTC by PrudinnikDmitriy

2022-10-27 12:52 UTC, PrudinnikDmitriy commented
https://app.clickup.com/t/3206k3q

2022-10-30 12:53 UTC, AndriiHrohodza requested changes

2022-10-31 08:37 UTC, PrudinnikDmitriy commented on assets/black-friday-scripts.js
> +      if (this.value.length === 0) {
@AndriiHrohodza  fixed

2022-10-31 09:59 UTC, AndriiHrohodza approved these changes

2022-10-31 13:04 UTC, yevheniitsuryk commented
@PrudinnikDmitriy https://bystrov.slack.com/archives/C03RHD1CESC/p1667221473783299

2022-11-01 17:29 UTC, yevheniitsuryk requested changes

2022-11-01 17:29 UTC, yevheniitsuryk commented on assets/black-friday-scripts.js
> +        document.getElementById('textOfError').style.visibility = "hidden";
@PrudinnikDmitriy formatting please
```suggestion
        document.getElementById('textOfError').style.visibility = 'hidden';
```

2022-11-01 17:29 UTC, yevheniitsuryk commented on assets/black-friday-scripts.js
> +    } else{
@PrudinnikDmitriy here too
```suggestion
    } else {
```

2022-11-02 13:42 UTC, PrudinnikDmitriy commented on assets/black-friday-scripts.js
> +        document.getElementById('textOfError').style.visibility = "hidden";
@yevheniitsuryk  fixed

2022-11-02 13:43 UTC, PrudinnikDmitriy commented on assets/black-friday-scripts.js
> +    } else{
@yevheniitsuryk fixed

2022-11-03 08:02 UTC, yevheniitsuryk approved these changes

2022-11-03 08:05 UTC, merged